env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  import/extensions:
    - error
    - ignorePackages
    - js: never
      ts: never
  no-param-reassign: off
